name: Update Taxi Data and Generate Map

on:
  workflow_dispatch:  # Manual trigger only

jobs:
  update-and-generate:
    runs-on: ubuntu-latest

    steps:
      - name: Checkout repo
        uses: actions/checkout@v3

      - name: Set up Python
        uses: actions/setup-python@v5
        with:
          python-version: '3.10'

      - name: Install Python dependencies
        run: |
          pip install folium requests

      - name: Call LTA Taxi API and save response
        env:
          ACCOUNT_KEY: ${{ secrets.ACCOUNT_KEY }}
        run: |
          curl -H "AccountKey: $ACCOUNT_KEY" -H "Accept: application/json" \
          "https://datamall2.mytransport.sg/ltaodataservice/Taxi-Availability" \
          -o taxi-data.json

      - name: Generate HTML map using folium
        run: |
          python generate_map.py

      - name: Commit and push updated files
        env:
          GITHUB_TOKEN: ${{ secrets.GITHUB_TOKEN }}
        run: |
          git config user.name "github-actions[bot]"
          git config user.email "github-actions[bot]@users.noreply.github.com"
          git add taxi-data.json index.html
          git diff --cached --quiet || git commit -m "Update taxi data and map"
          git push